"""Persisting the privacy vault, so an identity survives a restart.

The vault in ``privacy_vault`` is session state by construction: five in-memory
structures and a per-session key, dropped by ``clear`` and gone with the
process. That is the right default and this module does not change it. What it
adds is a seam for the deployment that needs the opposite, and one
implementation of that seam.

**A persisted vault is a different security object from an in-memory one.**
In memory it is an optimization: the plaintext it holds was already in the
caller's request. On disk it is a re-identification database, a single file
that maps every token a provider has seen back to the person behind it, and it
outlives the request, the process, and usually the incident. So this module
encrypts from its first commit rather than deferring it. A plaintext local
store would have been a smaller change and would have made the class docstring
in ``privacy_vault`` false in public.

**The caller supplies the key, and nothing here will invent one.** A key
generated by the library and written beside the ciphertext is not encryption at
rest; it is an obfuscated file plus a claim. ``generate_key`` exists to make a
key an operator can put in a secret manager, and there is no code path that
persists one. That is also why key *management* is a separate piece of work:
rotation, escrow, and a KMS-backed key all sit on top of this interface without
changing it.

**Continuity is what persistence buys, not protection.** Nothing crosses to the
provider that would not have crossed before: personal data is withheld either
way, and an unresolvable token still fails the call rather than resolving to
the wrong person. What a restart loses without a store is co-reference, so the
same person is issued a second token and a transcript from before the restart
stops resolving at all. That is an operational property, which is why the
ephemeral vault remains honest for deployments that do not need it.
"""

from __future__ import annotations

import base64
import json
import os
import secrets
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol, runtime_checkable

from guardllm.security.types import PIIClass

__all__ = [
    "VAULT_SNAPSHOT_VERSION",
    "SUPPORTED_VAULT_SNAPSHOT_VERSIONS",
    "EncryptedFileVaultStore",
    "MemoryVaultStore",
    "VaultEntry",
    "VaultSnapshot",
    "VaultStore",
    "VaultStoreError",
    "generate_key",
]


#: The version of the persisted snapshot format.
#:
#: A third long-lived interface, for the same reason as the policy file and the
#: Rego input document: a customer-hosted deployment writes this file with one
#: release and reads it with another, and a vault file that cannot be read is a
#: population of live tokens that stop resolving. Within a version, fields may
#: be ADDED and a reader that does not know them ignores them. No field is
#: removed, renamed, or given a new meaning. Anything else increments this.
VAULT_SNAPSHOT_VERSION = 1

#: Every version this build can read. An unrecognized one is refused rather
#: than guessed at, and newer is distinguished from retired because the
#: remedies are opposite.
SUPPORTED_VAULT_SNAPSHOT_VERSIONS = frozenset({1})

#: 256-bit keys only. Accepting a short key would let a deployment configure
#: itself down to a strength nobody chose, and there is no reason to offer the
#: choice: the operator generates the key with ``generate_key``.
KEY_BYTES = 32


class VaultStoreError(RuntimeError):
    """A snapshot could not be read or written.

    Always raised, never swallowed into an empty vault. Starting empty after a
    failed read looks like a fresh session and is not one: every token already
    in the host's transcript silently stops resolving, and the same people are
    re-tokenized under new identifiers.
    """


@dataclass(frozen=True)
class VaultEntry:
    """One issued token: the value, its class, and the codeword body.

    ``body`` rather than the rendered token, because everything else the vault
    indexes is derived from the body and storing the derived forms too would
    let a file disagree with itself.

    ``value`` is real plaintext and is excluded from ``repr`` for the reason
    the vault excludes it everywhere else: one traced or logged snapshot
    aggregates every identifier a session saw.
    """

    pii_class: PIIClass
    value: str = field(repr=False)
    body: str


@dataclass(frozen=True)
class VaultSnapshot:
    """Everything a vault needs to resume issuing and resolving.

    Deliberately not everything the vault holds. The payload index, the issued
    body set, and the trigram index are all functions of ``entries``, so they
    are rebuilt on load rather than stored: a stored index can be inconsistent
    with the entries it indexes, and the failure that causes is a token that
    resolves to the wrong person.

    ``source_key`` is here because it is not derivable. Past the source-handle
    cache cap the vault derives handles by HMAC under it, so a restart with a
    fresh key would re-label sources the model had already been shown.
    """

    entries: tuple[VaultEntry, ...] = ()
    #: (source_type, source_id, handle)
    sources: tuple[tuple[str, str, str], ...] = ()
    #: The per-session HMAC key for derived source handles.
    source_key: bytes = field(default=b"", repr=False)
    #: (normalized value, class) declared by the host, not detected.
    seeded: tuple[tuple[str, PIIClass], ...] = field(default=(), repr=False)
    version: int = VAULT_SNAPSHOT_VERSION

    def __repr__(self) -> str:
        return (
            f"VaultSnapshot(version={self.version}, entries={len(self.entries)}, "
            f"sources={len(self.sources)}, seeded={len(self.seeded)})"
        )


@runtime_checkable
class VaultStore(Protocol):
    """Where a snapshot goes between processes.

    Three methods, because a fourth would have to be a partial write and there
    is no correct partial write of this object: an entry list missing its
    source key resolves tokens while re-labelling sources.

    An implementation is free to be a database, a KMS-fronted blob, or a
    replicated store. What it must not be is lossy: returning a subset of a
    saved snapshot presents as a vault that forgot some people.
    """

    def load(self) -> VaultSnapshot | None:
        """The stored snapshot, or None when nothing has been stored yet.

        None means first run. It does not mean "unreadable": a store that
        cannot read what it holds raises ``VaultStoreError`` instead, so a
        wrong key is never mistaken for a new deployment.
        """
        ...

    def save(self, snapshot: VaultSnapshot) -> None:
        """Replace the stored snapshot. Atomic from a reader's point of view."""
        ...

    def purge(self) -> None:
        """Destroy the stored snapshot.

        Called by ``PrivacyVault.clear``. A clear that left the file behind
        would let a restart resurrect tokens the host has already invalidated.
        """
        ...


class MemoryVaultStore:
    """A store that holds one snapshot in memory.

    For tests, and for a deployment that wants the seam without a file: a
    gateway holding vaults for several sessions can put one of these behind
    each and keep its own persistence above them.
    """

    def __init__(self) -> None:
        self._snapshot: VaultSnapshot | None = None

    def load(self) -> VaultSnapshot | None:
        return self._snapshot

    def save(self, snapshot: VaultSnapshot) -> None:
        self._snapshot = snapshot

    def purge(self) -> None:
        self._snapshot = None


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------


def _to_json(snapshot: VaultSnapshot) -> bytes:
    document = {
        "version": snapshot.version,
        "source_key": base64.b64encode(snapshot.source_key).decode("ascii"),
        # Class by name, matching what render_token puts in the token itself.
        # The enum's value is the wire form elsewhere; using one form in both
        # places is how a rename would go unnoticed in exactly one of them.
        "entries": [
            {"class": e.pii_class.name, "value": e.value, "body": e.body} for e in snapshot.entries
        ],
        "sources": [list(s) for s in snapshot.sources],
        "seeded": [[value, cls.name] for value, cls in snapshot.seeded],
    }
    return json.dumps(document, separators=(",", ":")).encode("utf-8")


def _check_version(version: object) -> None:
    if isinstance(version, bool) or not isinstance(version, int):
        raise VaultStoreError(
            f"vault snapshot: version must be an integer, got {type(version).__name__}"
        )
    if version in SUPPORTED_VAULT_SNAPSHOT_VERSIONS:
        return
    if version > VAULT_SNAPSHOT_VERSION:
        raise VaultStoreError(
            f"vault snapshot: version {version} is newer than this build understands "
            f"(supports {sorted(SUPPORTED_VAULT_SNAPSHOT_VERSIONS)}). Upgrade guardllm "
            "rather than deleting the file: the entries it holds are live tokens."
        )
    raise VaultStoreError(
        f"vault snapshot: version {version} is no longer supported "
        f"(supports {sorted(SUPPORTED_VAULT_SNAPSHOT_VERSIONS)})."
    )


def _from_json(raw: bytes) -> VaultSnapshot:
    try:
        document = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise VaultStoreError(f"vault snapshot: not readable as JSON ({exc})") from exc
    if not isinstance(document, dict):
        raise VaultStoreError("vault snapshot: expected a JSON object")
    _check_version(document.get("version"))

    def _class(name: object, where: str) -> PIIClass:
        # An unknown class is refused rather than dropped. Dropping it would
        # discard live entries and leave the tokens for them in the host's
        # transcript resolving to nothing.
        try:
            return PIIClass[str(name)]
        except KeyError as exc:
            raise VaultStoreError(f"vault snapshot: unknown PII class {name!r} in {where}") from exc

    try:
        entries = tuple(
            VaultEntry(pii_class=_class(e["class"], "entries"), value=e["value"], body=e["body"])
            for e in document.get("entries", ())
        )
        sources = tuple((str(s[0]), str(s[1]), str(s[2])) for s in document.get("sources", ()))
        seeded = tuple((str(v), _class(c, "seeded")) for v, c in document.get("seeded", ()))
        source_key = base64.b64decode(document.get("source_key", ""), validate=True)
    except (KeyError, TypeError, IndexError, ValueError) as exc:
        raise VaultStoreError(f"vault snapshot: malformed document ({exc})") from exc

    return VaultSnapshot(
        entries=entries,
        sources=sources,
        source_key=source_key,
        seeded=seeded,
        version=int(document["version"]) if "version" in document else VAULT_SNAPSHOT_VERSION,
    )


# ---------------------------------------------------------------------------
# Encrypted local file
# ---------------------------------------------------------------------------

#: Header, and the AEAD's associated data. Binding the format version into the
#: authenticated data is what stops a future format being replayed as this one.
_MAGIC = b"GLVAULT1"
_NONCE_BYTES = 12


def _aesgcm():
    """AES-GCM from ``cryptography``, imported lazily.

    Optional for the same reason wasmtime is: the library's controls all work
    without it, and a core install should not carry a dependency it never
    calls. Not optional in the sense that a plaintext fallback exists, because
    there is no plaintext fallback: without this the store refuses to write.

    The stdlib has no AEAD, and the alternative to a well-reviewed dependency
    here is a hand-rolled construction in a security product, which is worse
    than the dependency by a wide margin.
    """
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError as exc:  # pragma: no cover - exercised by the extras test
        raise VaultStoreError(
            "an encrypted vault file needs the 'cryptography' package, which is not "
            "part of the core install. Install guardllm[vault]."
        ) from exc
    return AESGCM


def generate_key() -> str:
    """A fresh 256-bit key, base64, for an operator to store in a secret manager.

    Returned as text and never written anywhere by this library. Losing it
    means losing every token in the file, which is the intended property: a
    key recoverable from the deployment that holds the ciphertext is not
    protecting anything.
    """
    return base64.b64encode(secrets.token_bytes(KEY_BYTES)).decode("ascii")


def _coerce_key(key: bytes | str) -> bytes:
    if isinstance(key, str):
        try:
            key = base64.b64decode(key, validate=True)
        except ValueError as exc:
            raise VaultStoreError("vault key: not valid base64") from exc
    if len(key) != KEY_BYTES:
        raise VaultStoreError(
            f"vault key: must be {KEY_BYTES} bytes ({KEY_BYTES * 8} bits), got {len(key)}"
        )
    # An all-zero key is what an uninitialized buffer or an unset environment
    # variable decoded from a placeholder looks like. It is a valid AES key,
    # which is exactly the problem: the file would be encrypted under a
    # constant and would read back cleanly in the deployment that wrote it.
    if not any(key):
        raise VaultStoreError("vault key: refusing an all-zero key")
    return key


class EncryptedFileVaultStore:
    """One local file, AES-256-GCM, key supplied by the caller.

    The reference implementation of ``VaultStore``: enough for a single gateway
    that needs identity to survive a restart, and deliberately not more. It has
    no rotation, no escrow, no replication, and no access control beyond the
    file mode, all of which belong to key management rather than to the seam.

    What it does hold:

    - **Authenticated.** The header is associated data, so a truncated or
      edited file fails to open rather than opening short. Silent truncation
      would drop entries, and a dropped entry is a live token that stops
      resolving.
    - **Atomic.** Written to a temporary file in the same directory and moved
      into place, so a crash mid-write leaves the previous snapshot rather than
      half of the new one.
    - **0600.** Created through ``mkstemp``, which never has a readable moment.

    What it does not hold, said plainly: the *absence* of the file is not
    authenticated. Deleting it is indistinguishable from a first run, and the
    vault comes up empty. That is a denial of continuity, not a disclosure, and
    the remedy is filesystem permissions rather than cryptography.
    """

    def __init__(self, path: str | Path, *, key: bytes | str) -> None:
        self._path = Path(path)
        self._key = _coerce_key(key)

    @classmethod
    def from_env(
        cls, path: str | Path, *, var: str = "GUARDLLM_VAULT_KEY"
    ) -> EncryptedFileVaultStore:
        """Take the key from an environment variable holding base64.

        Refuses when the variable is unset rather than falling back to a
        generated key, because a generated key means the previous file is
        unreadable and the deployment would come up looking healthy and empty.
        """
        raw = os.environ.get(var)
        if not raw:
            raise VaultStoreError(
                f"vault key: {var} is not set. Generate one with "
                "guardllm.security.vault_store.generate_key() and store it in a secret manager."
            )
        return cls(path, key=raw)

    @property
    def path(self) -> Path:
        return self._path

    def load(self) -> VaultSnapshot | None:
        if not self._path.exists():
            return None
        blob = self._path.read_bytes()
        if len(blob) < len(_MAGIC) + _NONCE_BYTES:
            raise VaultStoreError(f"vault snapshot: {self._path} is too short to be a vault file")
        header, nonce, ciphertext = (
            blob[: len(_MAGIC)],
            blob[len(_MAGIC) : len(_MAGIC) + _NONCE_BYTES],
            blob[len(_MAGIC) + _NONCE_BYTES :],
        )
        if header != _MAGIC:
            raise VaultStoreError(f"vault snapshot: {self._path} is not a GuardLLM vault file")
        AESGCM = _aesgcm()
        try:
            plaintext = AESGCM(self._key).decrypt(nonce, ciphertext, header)
        except Exception as exc:
            # Deliberately one message for a wrong key and for a tampered file.
            # Distinguishing them tells an attacker which of the two they have.
            raise VaultStoreError(
                f"vault snapshot: {self._path} did not authenticate. The key is wrong "
                "or the file was modified; it is not being read as an empty vault."
            ) from exc
        return _from_json(plaintext)

    def save(self, snapshot: VaultSnapshot) -> None:
        AESGCM = _aesgcm()
        # A fresh random 96-bit nonce per write. Safe well past any realistic
        # number of writes under one key; rotation, which would raise that
        # ceiling further, is key management and sits above this class.
        nonce = secrets.token_bytes(_NONCE_BYTES)
        ciphertext = AESGCM(self._key).encrypt(nonce, _to_json(snapshot), _MAGIC)
        blob = _MAGIC + nonce + ciphertext

        parent = self._path.parent
        parent.mkdir(parents=True, exist_ok=True)
        # Same directory, so the replace below is a rename within one
        # filesystem and therefore atomic. mkstemp gives 0600 from creation.
        fd, tmp = tempfile.mkstemp(dir=str(parent), prefix=".vault-", suffix=".tmp")
        try:
            with os.fdopen(fd, "wb") as handle:
                handle.write(blob)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp, self._path)
        except BaseException:
            # A leftover temp file holds ciphertext under the live key. Not a
            # disclosure, but it is an unreferenced copy of the vault.
            try:
                os.unlink(tmp)
            except OSError:  # pragma: no cover - the replace already consumed it
                pass
            raise

    def purge(self) -> None:
        try:
            self._path.unlink()
        except FileNotFoundError:
            pass
